services:
  backend:
    build:
      context: ..
      dockerfile: shared/Dockerfile.backend
      target: prod
    container_name: app-build-prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    env_file:
      - ../backend/.env.production
    depends_on:
      - redis
      - dragonfly
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: app-redis-prod
    restart: unless-stopped
    ports:
      - "6379:6379"

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    container_name: app-dragonfly-prod
    restart: unless-stopped
    ports:
      - "6380:6379"
